name: test
on:
 repository_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create commits
        run: |
          date +%s > date.txt
          git add -A
          git commit -am "Modify tracked file during workflow"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3



