name: patch-to-pull-request
on:
 repository_dispatch:
jobs:
  patch-to-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create commits
        run: |
          printf "${{ github.event.client_payload.patch }}" | base64 -d | git apply
          echo "name=${{ github.event.client_payload.name || "unnamed.patch" }}" >> $GITHUB_ENV
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
         commit-message: "Apply patch ${{ env.name }}"
         title: "Apply patch ${{ env.name }} [patch-to-pull-request]"
         body: "Application of patch"
